const ADD_ACTIVITY = "ADD_ACTIVITY"
const REMOVE_ACTIVITY = "REMOVE_ACTIVITY"
const UPDATE_ACTIVITY = "UPDATE_ACTIVITY"
const GET_READY_TO_ADD_ACTIVITY = "GET_READY_TO_ADD_ACTIVITY"
const GET_READY_TO_STORE_ACTIVITIES = "GET_READY_TO_STORE_ACTIVITIES"
const STORE_ACTIVITIES ="STORE_ACTIVITIES"

const ADD_VALUE = "ADD_VALUE"
const REMOVE_VALUE = "REMOVE_VALUE"
const UPDATE_VALUE = "UPDATE_VALUE"
const GET_READY_TO_ADD_VALUE = "GET_READY_TO_ADD_VALUE"
const GET_READY_TO_STORE_VALUES = "GET_READY_TO_STORE_VALUES"
const STORE_VALUES = "STORE_VALUES"

const ADD_USER = "ADD_USER"
const GET_READY_TO_ADD_USER = "GET_READY_TO_ADD_USER"
const LOGIN_USER = "LOGIN_USER"
const GET_READY_TO_LOGIN_USER = "GET_READY_TO_LOGIN_USER"

const GET_READY_TO_STORE_TOKEN = "GET_READY_TO_STORE_TOKEN"
const STORE_TOKEN = "STORE_TOKEN"
const ADD_VALUE_TO_CURRENT_USER = "ADD_VALUE_TO_CURRENT_USER"
const GET_READY_TO_ADD_VALUE_TO_CURRENT_USER = "GET_READY_TO_ADD_VALUE_TO_CURRENT_USER"

export {
    ADD_ACTIVITY,
    REMOVE_ACTIVITY,
    UPDATE_ACTIVITY,
    GET_READY_TO_ADD_ACTIVITY,
    ADD_VALUE,
    REMOVE_VALUE,
    UPDATE_VALUE,
    ADD_USER,
    LOGIN_USER,
    GET_READY_TO_LOGIN_USER,
    GET_READY_TO_ADD_USER,
    GET_READY_TO_STORE_TOKEN,
    STORE_TOKEN,
    GET_READY_TO_ADD_VALUE,
    GET_READY_TO_STORE_VALUES,
    STORE_VALUES,
    GET_READY_TO_STORE_ACTIVITIES,
    STORE_ACTIVITIES,
    GET_READY_TO_ADD_VALUE_TO_CURRENT_USER,
    ADD_VALUE_TO_CURRENT_USER
}