const ADD_ACTIVITY = "ADD_ACTIVITY"
const REMOVE_ACTIVITY = "REMOVE_ACTIVITY"
const UPDATE_ACTIVITY = "UPDATE_ACTIVITY"

const ADD_VALUE = "ADD_VALUE"
const REMOVE_VALUE = "REMOVE_VALUE"
const UPDATE_VALUE = "UPDATE_VALUE"

const ADD_USER = "ADD_USER"
const GET_READY_TO_ADD_USER = "GET_READY_TO_ADD_USER"
const LOGIN_USER = "LOGIN_USER"
const GET_READY_TO_LOGIN_USER = "GET_READY_TO_LOGIN_USER"

const GET_READY_TO_STORE_TOKEN = "GET_READY_TO_STORE_TOKEN"
const STORE_TOKEN = "STORE_TOKEN"

export {
    ADD_ACTIVITY,
    REMOVE_ACTIVITY,
    UPDATE_ACTIVITY,
    ADD_VALUE,
    REMOVE_VALUE,
    UPDATE_VALUE,
    ADD_USER,
    LOGIN_USER,
    GET_READY_TO_LOGIN_USER,
    GET_READY_TO_ADD_USER,
    GET_READY_TO_STORE_TOKEN,
    STORE_TOKEN
}